import type { CameraPresetConfig, Hotspot3D } from './types';

export const CAMERA_PRESETS: CameraPresetConfig[] = [
  {
    id: 'overview',
    label: 'Общий вид завода',
    iconName: 'Globe',
    position: [0, 26, 46],
    target: [2, 5, 0],
    description: 'Панорамный обзор всего комплекса ЭЛОУ-АВТ-6 от ввода нефти до вакуумного блока',
  },
  {
    id: 'elou',
    label: 'Блок ЭЛОУ',
    iconName: 'Zap',
    position: [-18, 14, 22],
    target: [-18, 4, 0],
    description: 'Электродегидраторы Э-1..Э-6, насос промывки Н-82, буферная емкость Е-15',
  },
  {
    id: 'furnaces_at',
    label: 'Печи и АТ',
    iconName: 'Flame',
    position: [8, 16, 26],
    target: [8, 6, 0],
    description: 'Трубчатые печи П-1/П-3 с горелками и атмосферная колонна К-1 с тарелками',
  },
  {
    id: 'vt',
    label: 'Блок ВТ',
    iconName: 'RotateCcw',
    position: [27, 15, 22],
    target: [26, 5, 0],
    description: 'Вакуумная колонна К-2, эжекторная система и насосы откачки гудрона Н-4/Н-32',
  },
  {
    id: 'cinematic',
    label: '360° Облёт',
    iconName: 'Video',
    position: [0, 22, 44],
    target: [2, 5, 0],
    description: 'Плавный кинематографический облёт установки для презентаций и демо-стендов',
  },
];

export interface PlantHierarchyNode {
  id: string;
  equipmentId?: string;
  label: string;
  tag: string;
  type: 'unit' | 'vessel' | 'column' | 'furnace' | 'pump' | 'valve';
  cameraPosition: [number, number, number];
  cameraTarget: [number, number, number];
  children?: PlantHierarchyNode[];
}

export const PLANT_HIERARCHY: PlantHierarchyNode[] = [
  {
    id: 'unit-elou',
    label: 'Блок обессоливания и обезвоживания (ЭЛОУ)',
    tag: 'ЭЛОУ',
    type: 'unit',
    cameraPosition: [-19, 14, 22],
    cameraTarget: [-19, 4, 0],
    children: [
      {
        id: 'node-ed-battery',
        equipmentId: 'E_1',
        label: 'Электродегидраторы Э-1..Э-6 (I и II ступени)',
        tag: 'Э-1..Э-6',
        type: 'vessel',
        cameraPosition: [-18, 10, 15],
        cameraTarget: [-18, 3.5, 0],
      },
      {
        id: 'node-n82',
        equipmentId: 'N_82',
        label: 'Насос промывочной воды Н-82',
        tag: 'Н-82',
        type: 'pump',
        cameraPosition: [-28, 5, -2],
        cameraTarget: [-30, 1.5, -8],
      },
      {
        id: 'node-n1',
        equipmentId: 'N_1',
        label: 'Сырьевой насос подачи нефти в ЭЛОУ Н-1',
        tag: 'Н-1',
        type: 'pump',
        cameraPosition: [-24, 5, 4],
        cameraTarget: [-25, 1.5, -2],
      },
      {
        id: 'node-e15',
        equipmentId: 'E_15',
        label: 'Емкость дренажной и промывочной воды Е-15',
        tag: 'Е-15',
        type: 'vessel',
        cameraPosition: [-12, 6, 8],
        cameraTarget: [-12, 2.0, 0],
      },
    ],
  },
  {
    id: 'unit-furnaces',
    label: 'Печной блок нагрева сырья и мазута',
    tag: 'Печи',
    type: 'unit',
    cameraPosition: [3, 14, 22],
    cameraTarget: [3, 5, 0],
    children: [
      {
        id: 'node-p1',
        equipmentId: 'P_1',
        label: 'Трубчатая печь нагрева мазута П-1',
        tag: 'П-1',
        type: 'furnace',
        cameraPosition: [3, 12, 10],
        cameraTarget: [3, 6, -6],
      },
      {
        id: 'node-p3',
        equipmentId: 'P_3',
        label: 'Трубчатая печь контура колонны П-3',
        tag: 'П-3',
        type: 'furnace',
        cameraPosition: [3, 12, 18],
        cameraTarget: [3, 6, 6],
      },
      {
        id: 'node-n2',
        equipmentId: 'N_2',
        label: 'Насос подачи мазута в печь П-1 (Н-2)',
        tag: 'Н-2',
        type: 'pump',
        cameraPosition: [8, 5, 4],
        cameraTarget: [8, 1.5, -4],
      },
      {
        id: 'node-n3',
        equipmentId: 'N_3',
        label: 'Насос циркуляции печи П-3 (Н-3)',
        tag: 'Н-3',
        type: 'pump',
        cameraPosition: [8, 5, 8],
        cameraTarget: [8, 1.5, 4],
      },
    ],
  },
  {
    id: 'unit-at',
    label: 'Блок атмосферной перегонки (АТ)',
    tag: 'АТ',
    type: 'unit',
    cameraPosition: [13, 18, 25],
    cameraTarget: [13, 10, 0],
    children: [
      {
        id: 'node-k1',
        equipmentId: 'K_1',
        label: 'Ректификационная колонна К-1 (40 тарелок)',
        tag: 'К-1',
        type: 'column',
        cameraPosition: [13, 16, 18],
        cameraTarget: [13, 10, 0],
      },
      {
        id: 'node-n20',
        equipmentId: 'N_20',
        label: 'Сырьевой насос подачи в К-1 (Н-20)',
        tag: 'Н-20',
        type: 'pump',
        cameraPosition: [-4, 5, 8],
        cameraTarget: [-6, 1.5, 0],
      },
      {
        id: 'node-v1',
        equipmentId: 'V_1',
        label: 'Отсечной клапан подачи сырья V-1',
        tag: 'V-1',
        type: 'valve',
        cameraPosition: [-1, 4, 6],
        cameraTarget: [-2, 1.5, 0],
      },
      {
        id: 'node-v2',
        equipmentId: 'V_2',
        label: 'Клапан аварийного сброса паров V-2',
        tag: 'V-2',
        type: 'valve',
        cameraPosition: [14, 22, 10],
        cameraTarget: [13, 20.6, 0],
      },
    ],
  },
  {
    id: 'unit-vt',
    label: 'Блок вакуумной перегонки (ВТ)',
    tag: 'ВТ',
    type: 'unit',
    cameraPosition: [26, 18, 24],
    cameraTarget: [26, 9, 0],
    children: [
      {
        id: 'node-k2',
        equipmentId: 'K_2',
        label: 'Вакуумная колонна К-2 (глубокий вакуум)',
        tag: 'К-2',
        type: 'column',
        cameraPosition: [26, 15, 18],
        cameraTarget: [26, 8, 0],
      },
      {
        id: 'node-n4',
        equipmentId: 'N_4',
        label: 'Насос откачки гудрона Н-4',
        tag: 'Н-4',
        type: 'pump',
        cameraPosition: [29, 5, 8],
        cameraTarget: [30, 1.5, -3],
      },
      {
        id: 'node-n32',
        equipmentId: 'N_32',
        label: 'Резервный насос откачки гудрона Н-32',
        tag: 'Н-32',
        type: 'pump',
        cameraPosition: [29, 5, 8],
        cameraTarget: [32, 1.5, -3],
      },
      {
        id: 'node-v3',
        equipmentId: 'V_3',
        label: 'Отсечной клапан подачи мазута V-3',
        tag: 'V-3',
        type: 'valve',
        cameraPosition: [18, 5, 4],
        cameraTarget: [18, 1.6, -2.0],
      },
    ],
  },
];

export const TWIN_HOTSPOTS: Hotspot3D[] = [
  {
    id: 'hs-k1',
    label: 'К-1',
    sublabel: 'Атмосферная колонна',
    worldPos: [13, 22.5, 0.5],
    equipmentId: 'K_1',
    category: 'column',
    valueGetter: (sensors) => `T: ${(sensors.T_1 ?? 280).toFixed(1)}°C | P: ${(sensors.P_1 ?? 0.35).toFixed(3)} МПа | L: ${(sensors.L_1 ?? 50).toFixed(1)}%`,
  },
  {
    id: 'hs-k2',
    label: 'К-2',
    sublabel: 'Вакуумная колонна',
    worldPos: [26, 18.5, 0.5],
    equipmentId: 'K_2',
    category: 'column',
    valueGetter: (sensors) => `T: ${(sensors.T_2 ?? 350).toFixed(1)}°C | P: ${(sensors.P_vac ?? 0.04).toFixed(3)} МПа | L: ${(sensors.L_2 ?? 50).toFixed(1)}%`,
  },
  {
    id: 'hs-p1',
    label: 'П-1',
    sublabel: 'Печь нагрева мазута',
    worldPos: [3, 11.0, -6.5],
    equipmentId: 'P_1',
    category: 'furnace',
    valueGetter: (sensors, setpoints) => `Tфакт: ${(sensors.T_1 ?? 280).toFixed(1)}°C | Sp: ${(setpoints.T_1_Sp ?? 280).toFixed(0)}°C`,
  },
  {
    id: 'hs-p3',
    label: 'П-3',
    sublabel: 'Печь контура К-1',
    worldPos: [3, 13.5, 6.5],
    equipmentId: 'P_3',
    category: 'furnace',
    valueGetter: (sensors, setpoints) => `Tфакт: ${(sensors.T_3 ?? 280).toFixed(1)}°C | Sp: ${(setpoints.T_3_Sp ?? 280).toFixed(0)}°C`,
  },
  {
    id: 'hs-elou',
    label: 'ЭЛОУ',
    sublabel: 'Электродегидраторы Э-1..Э-6',
    worldPos: [-20, 8.0, 0],
    category: 'vessel',
    valueGetter: (sensors) => `Соли: ${(sensors.Sal_1 ?? 4.2).toFixed(1)} мг/л | Влага: ${(sensors.W_1 ?? 0.15).toFixed(2)}%`,
  },
  {
    id: 'hs-n82',
    label: 'Н-82',
    sublabel: 'Промывочная вода',
    worldPos: [-30, 3.2, -8.5],
    pumpId: 'N_82',
    equipmentId: 'N_82',
    category: 'pump',
  },
  {
    id: 'hs-n20',
    label: 'Н-20',
    sublabel: 'Сырьевой насос',
    worldPos: [-6, 3.2, 2.5],
    pumpId: 'N_20',
    equipmentId: 'N_20',
    category: 'pump',
  },
  {
    id: 'hs-v1',
    label: 'V-1',
    sublabel: 'Вход сырья',
    worldPos: [-2, 3.0, -1.2],
    valveId: 'V_1',
    equipmentId: 'V_1',
    category: 'valve',
  },
  {
    id: 'hs-v3',
    label: 'V-3',
    sublabel: 'Подача в К-2',
    worldPos: [18, 2.8, -2.0],
    valveId: 'V_3',
    equipmentId: 'V_3',
    category: 'valve',
  },
];

export const TWIN_THEMES = {
  dark: {
    background: 0x090e17,
    fog: 0x090e17,
    ground: 0x0d1522,
    groundGridPrimary: 0x223246,
    groundGridSecondary: 0x121c2b,
    concrete: 0x1c2636,
    steelDark: 0x223040,
    steelLight: 0x5a6d82,       // Четкая, благородная сталь с металлическим блеском
    steelBright: 0xc4d1de,      // Контрастные кольца и поручни
    steelTruss: 0x3b4c60,       // Четкая эстакада
    crudePipe: 0x10b981,
    gasPipe: 0xf59e0b,
    waterPipe: 0x0ea5e9,
    steamPipe: 0xe2e8f0,
    drainPipe: 0x64748b,
    ambientColor: 0x8ba2b8,
    ambientIntensity: 1.5,
    sunColor: 0xffffff,
    sunIntensity: 2.4,
    blueLightColor: 0x0284c7,
    blueLightIntensity: 1.2,
  },
  light: {
    background: 0xf1f5f9,
    fog: 0xf1f5f9,
    ground: 0xe2e8f0,
    groundGridPrimary: 0x94a3b8,
    groundGridSecondary: 0xcbd5e1,
    concrete: 0xd1d5db,
    steelDark: 0x334155,        // Контрастные графитовые юбки и основания
    steelLight: 0x8fa2b4,       // Светлая промышленная сталь (не черная!)
    steelBright: 0x1e293b,      // Контрастные темные акценты
    steelTruss: 0x475569,       // Графитовые балки эстакады
    crudePipe: 0x059669,
    gasPipe: 0xd97706,
    waterPipe: 0x0284c7,
    steamPipe: 0x64748b,
    drainPipe: 0x475569,
    ambientColor: 0xffffff,
    ambientIntensity: 2.0,
    sunColor: 0xfffbeb,
    sunIntensity: 2.8,
    blueLightColor: 0x38bdf8,
    blueLightIntensity: 0.9,
  },
};

export const TWIN_COLORS = {
  background: 0x070b12,
  ground: 0x0c121d,
  groundGrid: 0x1a293f,
  concrete: 0x242e3d,
  steelDark: 0x1f2937,
  steelLight: 0x475569,
  steelBright: 0x94a3b8,
  crudePipe: 0x10b981,
  gasPipe: 0xf59e0b,
  waterPipe: 0x0ea5e9,
  steamPipe: 0xe2e8f0,
  drainPipe: 0x64748b,
  pumpRunning: 0x10b981,
  pumpStopped: 0xef4444,
  flameOrange: 0xf97316,
  flameYellow: 0xfde047,
  flameBlue: 0x38bdf8,
};
