import type { MnemoschemeConfig } from './types';

export const DEFAULT_MNEMOSCHEME_ID = 'elou-avt-6-default';

export const DEFAULT_MNEMOSCHEME_PRESET: MnemoschemeConfig = {
  id: DEFAULT_MNEMOSCHEME_ID,
  name: 'ЭЛОУ-АВТ-6 (Штатный регламент)',
  description: 'Эталонная технологическая мнемосхема ЭЛОУ-АВТ-6 с полным контуром ЭЛОУ, колонн К-1/К-2, печей П-1/П-3 и насосных агрегатов',
  isBuiltin: true,
  width: 1260,
  height: 620,
  zones: [
    { id: 'zone-elou', x: 10, y: 10, width: 380, height: 600, label: 'ЭЛОУ' },
    { id: 'zone-k1', x: 400, y: 10, width: 390, height: 600, label: 'АТ' },
    { id: 'zone-k2', x: 800, y: 10, width: 450, height: 600, label: 'ВТ' },
  ],
  columns: [
    {
      id: 'col-k1',
      tag: 'К-1',
      equipmentId: 'K_1',
      x: 410,
      y: 120,
      levelBinding: 'L_1',
      alertBindings: ['steam_fail', 'valve_jam', 'power_fail'],
    },
    {
      id: 'col-k2',
      tag: 'К-2',
      equipmentId: 'K_2',
      x: 900,
      y: 160,
      levelBinding: 'L_2',
      alertBindings: ['vt_vacuum_loss', 'k2_pump_fail', 'steam_fail', 'power_fail'],
      tagOffsetY: 112,
    },
  ],
  furnaces: [
    {
      id: 'fur-p3',
      tag: 'П-3',
      equipmentId: 'P_3',
      x: 130,
      y: 430,
      flameBinding: 'Flame_P3',
      alertBindings: ['power_fail'],
    },
    {
      id: 'fur-p1',
      tag: 'П-1',
      equipmentId: 'P_1',
      x: 650,
      y: 430,
      flameBinding: 'Flame_P1',
      alertBindings: ['coil_overheat', 'power_fail'],
    },
  ],
  vessels: [
    {
      id: 'ves-e1',
      tag: 'Е-1',
      equipmentId: 'VESSEL_E_1',
      x: 620,
      y: 50,
      levelSensorBinding: 'L_E1',
      alertBindings: ['valve_jam', 'power_fail'],
    },
    {
      id: 'ves-e2',
      tag: 'Е-2',
      equipmentId: 'VESSEL_E_2',
      x: 1100,
      y: 70,
      levelSensorBinding: 'L_E2',
      alertBindings: ['vt_vacuum_loss', 'power_fail'],
    },
  ],
  pumps: [
    {
      id: 'pump-n20',
      tag: 'Н-20',
      equipmentId: 'N_20',
      x: 150,
      y: 100,
      alertBindings: ['pump_fail', 'power_fail'],
    },
    {
      id: 'pump-n3',
      tag: 'Н-3',
      equipmentId: 'N_3',
      x: 320,
      y: 470,
      direction: 'left',
      alertBindings: ['power_fail'],
    },
    {
      id: 'pump-n2',
      tag: 'Н-2',
      equipmentId: 'N_2',
      x: 580,
      y: 470,
      alertBindings: ['power_fail'],
    },
    {
      id: 'pump-n32',
      tag: 'Н-32',
      equipmentId: 'N_32',
      x: 1080,
      y: 490,
      tagOffsetY: -39,
      alertBindings: ['k2_pump_fail', 'power_fail'],
    },
    {
      id: 'pump-n4',
      tag: 'Н-4',
      equipmentId: 'N_4',
      x: 1080,
      y: 570,
      tagOffsetY: -39,
      alertBindings: ['k2_pump_fail', 'power_fail'],
    },
  ],
  valves: [
    {
      id: 'valve-v-elou',
      label: 'V-ELOU',
      valveId: 'V_ELOU',
      equipmentId: 'V_ELOU',
      x: 80,
      y: 60,
      rotate: 90,
      vertical: true,
      hideLabel: true,
    },
    {
      id: 'valve-v1',
      label: 'V-1',
      valveId: 'V_1',
      equipmentId: 'V_1',
      x: 310,
      y: 190,
    },
    {
      id: 'valve-v2',
      label: 'V-2',
      valveId: 'V_2',
      equipmentId: 'V_2',
      x: 480,
      y: 50,
      rotate: 90,
      vertical: true,
    },
    {
      id: 'valve-ve1-drain',
      label: 'ДРЕН Е-1',
      valveId: 'V_E1_DRAIN',
      x: 680,
      y: 120,
      rotate: 90,
      vertical: true,
      hideLabel: true,
    },
    {
      id: 'valve-steam-k1',
      label: 'ПАР К-1',
      valveId: 'V_STEAM_K1',
      x: 570,
      y: 240,
    },
    {
      id: 'valve-vp3-1',
      label: 'V-П3-1',
      valveId: 'V_P3_OUT',
      x: 260,
      y: 470,
    },
    {
      id: 'valve-vp3-2',
      label: 'V-П3-2',
      valveId: 'V_P3_RETURN',
      x: 290,
      y: 280,
    },
    {
      id: 'valve-fuel-p3',
      label: 'ТОПЛ. П-3',
      valveId: 'FUEL_P3',
      x: 180,
      y: 530,
      rotate: 90,
      vertical: true,
      hideLabel: true,
    },
    {
      id: 'valve-vp1',
      label: 'V-П1',
      valveId: 'V_P1_IN',
      x: 630,
      y: 470,
    },
    {
      id: 'valve-v3',
      label: 'V-3',
      valveId: 'V_3',
      equipmentId: 'V_3',
      x: 820,
      y: 350,
      rotate: 90,
      vertical: true,
    },
    {
      id: 'valve-fuel-p1',
      label: 'ТОПЛ. П-1',
      valveId: 'FUEL_P1',
      x: 700,
      y: 530,
      rotate: 90,
      vertical: true,
      hideLabel: true,
    },
    {
      id: 'valve-vk2-relief',
      label: 'СБРОС К-2',
      valveId: 'V_K2_RELIEF',
      x: 960,
      y: 60,
      rotate: 90,
      vertical: true,
    },
    {
      id: 'valve-ve2-drain',
      label: 'ДРЕН Е-2',
      valveId: 'V_E2_DRAIN',
      x: 1160,
      y: 140,
      rotate: 90,
      vertical: true,
      hideLabel: true,
    },
    {
      id: 'valve-steam-k2',
      label: 'ПАР К-2',
      valveId: 'V_STEAM_K2',
      x: 1140,
      y: 270,
      hideLabel: true,
    },
    {
      id: 'valve-vk2-out-32',
      label: 'V-Н32',
      valveId: 'V_K2_OUT_32',
      x: 1180,
      y: 490,
    },
    {
      id: 'valve-vk2-out-4',
      label: 'V-Н4',
      valveId: 'V_K2_OUT_4',
      x: 1180,
      y: 570,
    },
  ],
  sensors: [
    {
      id: 'sensor-sal1',
      tag: 'Sal-1',
      sensorKey: 'Sal_1',
      unit: 'мг/л',
      x: 90,
      y: 170,
    },
    {
      id: 'sensor-w1',
      tag: 'W-1',
      sensorKey: 'W_1',
      unit: '%',
      x: 180,
      y: 170,
    },
    {
      id: 'sensor-p1',
      tag: 'P-1 · К-1',
      sensorKey: 'P_1',
      unit: 'МПа',
      x: 590,
      y: 190,
      showSparkline: true,
      minLimit: 0.05,
      maxLimit: 0.5,
    },
    {
      id: 'sensor-l1',
      tag: 'L-1 · К-1',
      sensorKey: 'L_1',
      unit: '%',
      x: 620,
      y: 330,
      showLevelGauge: true,
      fullScaleMm: 2000,
    },
    {
      id: 'sensor-t1',
      tag: 'T-1 · П-1',
      sensorKey: 'T_1',
      unit: '°C',
      x: 700,
      y: 390,
      showSparkline: true,
      minLimit: 240,
      maxLimit: 380,
    },
    {
      id: 'sensor-t3',
      tag: 'T-3 · П-3',
      sensorKey: 'T_3',
      unit: '°C',
      x: 180,
      y: 390,
      showSparkline: true,
      minLimit: 240,
      maxLimit: 380,
    },
    {
      id: 'sensor-pvac',
      tag: 'P-vac · К-2',
      sensorKey: 'P_vac',
      unit: 'МПа',
      x: 1100,
      y: 210,
    },
    {
      id: 'sensor-t2',
      tag: 'T-2 · К-2',
      sensorKey: 'T_2',
      unit: '°C',
      x: 1100,
      y: 340,
      showSparkline: true,
      minLimit: 180,
      maxLimit: 420,
    },
    {
      id: 'sensor-l2',
      tag: 'L-2 · К-2',
      sensorKey: 'L_2',
      unit: '%',
      x: 1100,
      y: 410,
      showLevelGauge: true,
      fullScaleMm: 4000,
    },
  ],
  pipes: [
    { id: 'pipe-feed-in', d: 'M 60,100 H 120', kind: 'crude' },
    { id: 'pipe-demulsifier', d: 'M 80,30 V 100', kind: 'demulsifier', flowBinding: 'demulsifier' },
    { id: 'pipe-feed-k1', d: 'M 180,100 H 250 V 190 H 410', kind: 'crude', flowBinding: 'k1Feed', cutOffValve: 'V_1' },
    { id: 'pipe-gas-relief-1', d: 'M 480,70 H 620', kind: 'gas', flowBinding: 'k1Relief' },
    { id: 'pipe-gas-flare-1', d: 'M 480,120 V 30 H 580', kind: 'gas', flowBinding: 'k1Relief' },
    { id: 'pipe-drain-e1', kind: 'drain', flowBinding: 'e1Drain', x1: 680, y1: 90, x2: 680, y2: 140 },
    { id: 'pipe-steam-k1', kind: 'steam', flowBinding: 'steamK1', x1: 610, y1: 240, x2: 540, y2: 240 },
    { id: 'pipe-k1-bottom', d: 'M 480,410 V 470', kind: 'crude', flowBinding: 'k1BottomOutflow' },
    { id: 'pipe-k1-loop-p3', d: 'M 480,470 H 350', kind: 'crude', flowBinding: 'k1Loop' },
    { id: 'pipe-h3-to-p3', d: 'M 300,470 H 220', kind: 'crude', flowBinding: 'k1Loop', cutOffValve: 'V_P3_OUT' },
    { id: 'pipe-p3-to-k1', d: 'M 130,470 H 70 V 280 H 410', kind: 'crude', flowBinding: 'k1Loop', cutOffValve: 'V_P3_RETURN' },
    { id: 'pipe-fuel-p3', kind: 'fuel', flowBinding: 'fuelP3', x1: 180, y1: 500, x2: 180, y2: 550 },
    { id: 'pipe-steam-p3', kind: 'steam', x1: 130, y1: 450, x2: 90, y2: 450 },
    { id: 'pipe-k1-to-h2', d: 'M 480,470 H 550', kind: 'crude', flowBinding: 'k2Feed' },
    { id: 'pipe-h2-to-p1', d: 'M 610,470 H 650', kind: 'crude', flowBinding: 'k2Feed', cutOffValve: 'V_P1_IN' },
    { id: 'pipe-p1-to-k2', d: 'M 740,470 H 820 V 250 H 900', kind: 'crude', flowBinding: 'k2Feed', cutOffValve: 'V_3' },
    { id: 'pipe-fuel-p1', kind: 'fuel', flowBinding: 'fuelP1', x1: 700, y1: 500, x2: 700, y2: 550 },
    { id: 'pipe-steam-p1', kind: 'steam', x1: 740, y1: 450, x2: 790, y2: 450 },
    { id: 'pipe-gas-relief-2', d: 'M 960,90 H 1100', kind: 'gas', flowBinding: 'k2Relief' },
    { id: 'pipe-gas-flare-2', d: 'M 960,160 V 30 H 1080', kind: 'gas', flowBinding: 'k2Relief' },
    { id: 'pipe-drain-e2', kind: 'drain', flowBinding: 'e2Drain', x1: 1160, y1: 110, x2: 1160, y2: 160 },
    { id: 'pipe-steam-k2', kind: 'steam', flowBinding: 'steamK2', x1: 1240, y1: 270, x2: 1010, y2: 270 },
    { id: 'pipe-k2-to-h32', d: 'M 960,450 V 490 H 1050', kind: 'crude', flowBinding: 'k2Outflow32' },
    { id: 'pipe-h32-out', d: 'M 1100,490 H 1240', kind: 'crude', flowBinding: 'k2Outflow32', cutOffValve: 'V_K2_OUT_32' },
    { id: 'pipe-k2-to-h4', d: 'M 960,490 V 570 H 1050', kind: 'crude', flowBinding: 'k2Outflow4' },
    { id: 'pipe-h4-out', d: 'M 1100,570 H 1240', kind: 'crude', flowBinding: 'k2Outflow4', cutOffValve: 'V_K2_OUT_4' },
  ],
  labels: [
    { id: 'lbl-elou', x: 20, y: 110, text: 'ЭЛОУ', className: 'source-label' },
    { id: 'lbl-demuls-1', x: 220, y: 30, text: 'ДЕЭМУЛЬГАТОР', className: 'utility-label' },
    { id: 'lbl-demuls-2', x: 220, y: 50, text: 'В ЭЛОУ', className: 'utility-label' },
    { id: 'lbl-v-elou', x: 80, y: 20, text: 'V-ELOU', className: 'valve-tag' },
    { id: 'lbl-gas-1', x: 510, y: 20, text: 'СБРОС ГАЗА', className: 'gas-release-label' },
    { id: 'lbl-drain-e1-1', x: 700, y: 130, text: 'ДРЕН Е-1', className: 'utility-label' },
    { id: 'lbl-drain-e1-2', x: 700, y: 150, text: 'ДРЕНАЖ', className: 'utility-label' },
    { id: 'lbl-steam-k1', x: 530, y: 230, text: 'ПАР', className: 'utility-label', textAnchor: 'end' },
    { id: 'lbl-fuel-p3-1', x: 220, y: 540, text: 'ТОПЛ. П-3', className: 'utility-label' },
    { id: 'lbl-fuel-p3-2', x: 180, y: 580, text: 'ТОПЛИВО', className: 'utility-label', textAnchor: 'middle' },
    { id: 'lbl-steam-p3', x: 50, y: 440, text: 'ПАР', className: 'utility-label' },
    { id: 'lbl-fuel-p1-1', x: 740, y: 540, text: 'ТОПЛ. П-1', className: 'utility-label' },
    { id: 'lbl-fuel-p1-2', x: 700, y: 580, text: 'ТОПЛИВО', className: 'utility-label', textAnchor: 'middle' },
    { id: 'lbl-steam-p1', x: 800, y: 440, text: 'ПАР', className: 'utility-label' },
    { id: 'lbl-gas-2', x: 1000, y: 20, text: 'СБРОС ГАЗА', className: 'gas-release-label' },
    { id: 'lbl-drain-e2-1', x: 1180, y: 150, text: 'ДРЕН Е-2', className: 'utility-label' },
    { id: 'lbl-drain-e2-2', x: 1180, y: 170, text: 'ДРЕНАЖ', className: 'utility-label' },
    { id: 'lbl-steam-k2', x: 1140, y: 230, text: 'ОТПАРНОЙ ПАР К-2', className: 'utility-label', textAnchor: 'middle' },
  ],
};

export const BUILTIN_PRESETS: MnemoschemeConfig[] = [
  DEFAULT_MNEMOSCHEME_PRESET,
];
