import type { MnemoschemeConfig } from './types';

export const DEFAULT_MNEMOSCHEME_ID = 'elou-avt-6-default';

export const DEFAULT_MNEMOSCHEME_PRESET: MnemoschemeConfig = {
  id: DEFAULT_MNEMOSCHEME_ID,
  name: 'ЭЛОУ-АВТ-6 (Штатный регламент)',
  description: 'Эталонная технологическая мнемосхема ЭЛОУ-АВТ-6 с полным контуром ЭЛОУ, колонн К-1/К-2, печей П-1/П-3 и насосных агрегатов',
  isBuiltin: true,
  width: 1260,
  height: 620,
  zones: [
    { id: 'zone-elou', x: 12, y: 8, width: 384, height: 596, label: 'ЭЛОУ' },
    { id: 'zone-k1', x: 400, y: 8, width: 386, height: 596, label: 'АТ' },
    { id: 'zone-k2', x: 790, y: 8, width: 458, height: 596, label: 'ВТ' },
  ],
  columns: [
    {
      id: 'col-k1',
      tag: 'К-1',
      equipmentId: 'K_1',
      x: 410,
      y: 120,
      levelBinding: 'L_1',
      alertBindings: ['steam_fail', 'valve_jam', 'power_fail'],
    },
    {
      id: 'col-k2',
      tag: 'К-2',
      equipmentId: 'K_2',
      x: 900,
      y: 160,
      levelBinding: 'L_2',
      alertBindings: ['vt_vacuum_loss', 'k2_pump_fail', 'steam_fail', 'power_fail'],
      tagOffsetY: 112,
    },
  ],
  furnaces: [
    {
      id: 'fur-p3',
      tag: 'П-3',
      equipmentId: 'P_3',
      x: 130,
      y: 430,
      flameBinding: 'Flame_P3',
      alertBindings: ['power_fail'],
    },
    {
      id: 'fur-p1',
      tag: 'П-1',
      equipmentId: 'P_1',
      x: 650,
      y: 430,
      flameBinding: 'Flame_P1',
      alertBindings: ['coil_overheat', 'power_fail'],
    },
  ],
  vessels: [
    {
      id: 'ves-e1',
      tag: 'Е-1',
      equipmentId: 'VESSEL_E_1',
      x: 620,
      y: 47,
      levelSensorBinding: 'L_E1',
      alertBindings: ['valve_jam', 'power_fail'],
    },
    {
      id: 'ves-e2',
      tag: 'Е-2',
      equipmentId: 'VESSEL_E_2',
      x: 1095,
      y: 69,
      levelSensorBinding: 'L_E2',
      alertBindings: ['vt_vacuum_loss', 'power_fail'],
    },
  ],
  pumps: [
    {
      id: 'pump-n20',
      tag: 'Н-20',
      equipmentId: 'N_20',
      x: 150,
      y: 104,
      alertBindings: ['pump_fail', 'power_fail'],
    },
    {
      id: 'pump-n3',
      tag: 'Н-3',
      equipmentId: 'N_3',
      x: 324,
      y: 466,
      direction: 'left',
      alertBindings: ['power_fail'],
    },
    {
      id: 'pump-n2',
      tag: 'Н-2',
      equipmentId: 'N_2',
      x: 583,
      y: 466,
      alertBindings: ['power_fail'],
    },
    {
      id: 'pump-n32',
      tag: 'Н-32',
      equipmentId: 'N_32',
      x: 1080,
      y: 492,
      tagOffsetY: -39,
      alertBindings: ['k2_pump_fail', 'power_fail'],
    },
    {
      id: 'pump-n4',
      tag: 'Н-4',
      equipmentId: 'N_4',
      x: 1080,
      y: 566,
      tagOffsetY: -39,
      alertBindings: ['k2_pump_fail', 'power_fail'],
    },
  ],
  valves: [
    {
      id: 'valve-v-elou',
      label: 'V-ELOU',
      valveId: 'V_ELOU',
      equipmentId: 'V_ELOU',
      x: 82,
      y: 64,
      rotate: 90,
      vertical: true,
      hideLabel: true,
    },
    {
      id: 'valve-v1',
      label: 'V-1',
      valveId: 'V_1',
      equipmentId: 'V_1',
      x: 310,
      y: 190,
    },
    {
      id: 'valve-v2',
      label: 'V-2',
      valveId: 'V_2',
      equipmentId: 'V_2',
      x: 475,
      y: 48,
      rotate: 90,
      vertical: true,
    },
    {
      id: 'valve-ve1-drain',
      label: 'ДРЕН Е-1',
      valveId: 'V_E1_DRAIN',
      x: 680,
      y: 118,
      rotate: 90,
      vertical: true,
      hideLabel: true,
    },
    {
      id: 'valve-steam-k1',
      label: 'ПАР К-1',
      valveId: 'V_STEAM_K1',
      x: 575,
      y: 235,
    },
    {
      id: 'valve-vp3-1',
      label: 'V-П3-1',
      valveId: 'V_P3_OUT',
      x: 258,
      y: 466,
    },
    {
      id: 'valve-vp3-2',
      label: 'V-П3-2',
      valveId: 'V_P3_RETURN',
      x: 290,
      y: 278,
    },
    {
      id: 'valve-fuel-p3',
      label: 'ТОПЛ. П-3',
      valveId: 'FUEL_P3',
      x: 175,
      y: 525,
      rotate: 90,
      vertical: true,
      hideLabel: true,
    },
    {
      id: 'valve-vp1',
      label: 'V-П1',
      valveId: 'V_P1_IN',
      x: 625,
      y: 466,
    },
    {
      id: 'valve-v3',
      label: 'V-3',
      valveId: 'V_3',
      equipmentId: 'V_3',
      x: 820,
      y: 345,
      rotate: 90,
      vertical: true,
    },
    {
      id: 'valve-fuel-p1',
      label: 'ТОПЛ. П-1',
      valveId: 'FUEL_P1',
      x: 695,
      y: 525,
      rotate: 90,
      vertical: true,
      hideLabel: true,
    },
    {
      id: 'valve-vk2-relief',
      label: 'СБРОС К-2',
      valveId: 'V_K2_RELIEF',
      x: 965,
      y: 56,
      rotate: 90,
      vertical: true,
    },
    {
      id: 'valve-ve2-drain',
      label: 'ДРЕН Е-2',
      valveId: 'V_E2_DRAIN',
      x: 1155,
      y: 139,
      rotate: 90,
      vertical: true,
      hideLabel: true,
    },
    {
      id: 'valve-steam-k2',
      label: 'ПАР К-2',
      valveId: 'V_STEAM_K2',
      x: 1140,
      y: 265,
      hideLabel: true,
    },
    {
      id: 'valve-vk2-out-32',
      label: 'V-Н32',
      valveId: 'V_K2_OUT_32',
      x: 1180,
      y: 492,
    },
    {
      id: 'valve-vk2-out-4',
      label: 'V-Н4',
      valveId: 'V_K2_OUT_4',
      x: 1180,
      y: 566,
    },
  ],
  sensors: [
    {
      id: 'sensor-sal1',
      tag: 'Sal-1',
      sensorKey: 'Sal_1',
      unit: 'мг/л',
      x: 92,
      y: 170,
    },
    {
      id: 'sensor-w1',
      tag: 'W-1',
      sensorKey: 'W_1',
      unit: '%',
      x: 180,
      y: 170,
    },
    {
      id: 'sensor-p1',
      tag: 'P-1 · К-1',
      sensorKey: 'P_1',
      unit: 'МПа',
      x: 585,
      y: 190,
      showSparkline: true,
      minLimit: 0.05,
      maxLimit: 0.5,
    },
    {
      id: 'sensor-l1',
      tag: 'L-1 · К-1',
      sensorKey: 'L_1',
      unit: '%',
      x: 615,
      y: 330,
      showLevelGauge: true,
      fullScaleMm: 2000,
    },
    {
      id: 'sensor-t1',
      tag: 'T-1 · П-1',
      sensorKey: 'T_1',
      unit: '°C',
      x: 695,
      y: 390,
      showSparkline: true,
      minLimit: 240,
      maxLimit: 380,
    },
    {
      id: 'sensor-t3',
      tag: 'T-3 · П-3',
      sensorKey: 'T_3',
      unit: '°C',
      x: 175,
      y: 390,
      showSparkline: true,
      minLimit: 240,
      maxLimit: 380,
    },
    {
      id: 'sensor-pvac',
      tag: 'P-vac · К-2',
      sensorKey: 'P_vac',
      unit: 'МПа',
      x: 1100,
      y: 205,
    },
    {
      id: 'sensor-t2',
      tag: 'T-2 · К-2',
      sensorKey: 'T_2',
      unit: '°C',
      x: 1100,
      y: 335,
      showSparkline: true,
      minLimit: 180,
      maxLimit: 420,
    },
    {
      id: 'sensor-l2',
      tag: 'L-2 · К-2',
      sensorKey: 'L_2',
      unit: '%',
      x: 1100,
      y: 410,
      showLevelGauge: true,
      fullScaleMm: 4000,
    },
  ],
  pipes: [
    { id: 'pipe-feed-in', d: 'M 60,104 H 120', kind: 'crude' },
    { id: 'pipe-demulsifier', d: 'M 82,28 V 94', kind: 'demulsifier', flowBinding: 'demulsifier' },
    { id: 'pipe-feed-k1', d: 'M 180,104 H 250 V 190 H 410', kind: 'crude', flowBinding: 'k1Feed', cutOffValve: 'V_1' },
    { id: 'pipe-gas-relief-1', d: 'M 475,70 H 620', kind: 'gas', flowBinding: 'k1Relief' },
    { id: 'pipe-gas-flare-1', d: 'M 475,120 V 28 H 585', kind: 'gas', flowBinding: 'k1Relief' },
    { id: 'pipe-drain-e1', kind: 'drain', flowBinding: 'e1Drain', x1: 680, y1: 93, x2: 680, y2: 142 },
    { id: 'pipe-steam-k1', kind: 'steam', flowBinding: 'steamK1', x1: 605, y1: 235, x2: 540, y2: 235 },
    { id: 'pipe-k1-bottom', d: 'M 475,410 V 466', kind: 'crude', flowBinding: 'k1BottomOutflow' },
    { id: 'pipe-k1-loop-p3', d: 'M 475,466 H 352', kind: 'crude', flowBinding: 'k1Loop' },
    { id: 'pipe-h3-to-p3', d: 'M 302,466 H 220', kind: 'crude', flowBinding: 'k1Loop', cutOffValve: 'V_P3_OUT' },
    { id: 'pipe-p3-to-k1', d: 'M 130,466 H 72 V 278 H 410', kind: 'crude', flowBinding: 'k1Loop', cutOffValve: 'V_P3_RETURN' },
    { id: 'pipe-fuel-p3', kind: 'fuel', flowBinding: 'fuelP3', x1: 175, y1: 502, x2: 175, y2: 548 },
    { id: 'pipe-steam-p3', kind: 'steam', x1: 130, y1: 446, x2: 92, y2: 446 },
    { id: 'pipe-k1-to-h2', d: 'M 475,466 H 555', kind: 'crude', flowBinding: 'k2Feed' },
    { id: 'pipe-h2-to-p1', d: 'M 605,466 H 650', kind: 'crude', flowBinding: 'k2Feed', cutOffValve: 'V_P1_IN' },
    { id: 'pipe-p1-to-k2', d: 'M 740,466 H 820 V 250 H 900', kind: 'crude', flowBinding: 'k2Feed', cutOffValve: 'V_3' },
    { id: 'pipe-fuel-p1', kind: 'fuel', flowBinding: 'fuelP1', x1: 695, y1: 502, x2: 695, y2: 548 },
    { id: 'pipe-steam-p1', kind: 'steam', x1: 740, y1: 446, x2: 790, y2: 446 },
    { id: 'pipe-gas-relief-2', d: 'M 965,92 H 1095', kind: 'gas', flowBinding: 'k2Relief' },
    { id: 'pipe-gas-flare-2', d: 'M 965,160 V 28 H 1080', kind: 'gas', flowBinding: 'k2Relief' },
    { id: 'pipe-drain-e2', kind: 'drain', flowBinding: 'e2Drain', x1: 1155, y1: 115, x2: 1155, y2: 164 },
    { id: 'pipe-steam-k2', kind: 'steam', flowBinding: 'steamK2', x1: 1245, y1: 265, x2: 1008, y2: 265 },
    { id: 'pipe-k2-to-h32', d: 'M 965,450 V 492 H 1052', kind: 'crude', flowBinding: 'k2Outflow32' },
    { id: 'pipe-h32-out', d: 'M 1102,492 H 1245', kind: 'crude', flowBinding: 'k2Outflow32', cutOffValve: 'V_K2_OUT_32' },
    { id: 'pipe-k2-to-h4', d: 'M 965,492 V 566 H 1052', kind: 'crude', flowBinding: 'k2Outflow4' },
    { id: 'pipe-h4-out', d: 'M 1102,566 H 1245', kind: 'crude', flowBinding: 'k2Outflow4', cutOffValve: 'V_K2_OUT_4' },
  ],
  labels: [
    { id: 'lbl-elou', x: 18, y: 110, text: 'ЭЛОУ', className: 'source-label' },
    { id: 'lbl-demuls-1', x: 216, y: 34, text: 'ДЕЭМУЛЬГАТОР', className: 'utility-label' },
    { id: 'lbl-demuls-2', x: 216, y: 49, text: 'В ЭЛОУ', className: 'utility-label' },
    { id: 'lbl-v-elou', x: 82, y: 19, text: 'V-ELOU', className: 'valve-tag' },
    { id: 'lbl-gas-1', x: 505, y: 18, text: 'СБРОС ГАЗА', className: 'gas-release-label' },
    { id: 'lbl-drain-e1-1', x: 704, y: 132, text: 'ДРЕН Е-1', className: 'utility-label' },
    { id: 'lbl-drain-e1-2', x: 704, y: 151, text: 'ДРЕНАЖ', className: 'utility-label' },
    { id: 'lbl-steam-k1', x: 532, y: 228, text: 'ПАР', className: 'utility-label', textAnchor: 'end' },
    { id: 'lbl-fuel-p3-1', x: 215, y: 536, text: 'ТОПЛ. П-3', className: 'utility-label' },
    { id: 'lbl-fuel-p3-2', x: 175, y: 575, text: 'ТОПЛИВО', className: 'utility-label', textAnchor: 'middle' },
    { id: 'lbl-steam-p3', x: 48, y: 440, text: 'ПАР', className: 'utility-label' },
    { id: 'lbl-fuel-p1-1', x: 735, y: 536, text: 'ТОПЛ. П-1', className: 'utility-label' },
    { id: 'lbl-fuel-p1-2', x: 695, y: 575, text: 'ТОПЛИВО', className: 'utility-label', textAnchor: 'middle' },
    { id: 'lbl-steam-p1', x: 798, y: 440, text: 'ПАР', className: 'utility-label' },
    { id: 'lbl-gas-2', x: 995, y: 18, text: 'СБРОС ГАЗА', className: 'gas-release-label' },
    { id: 'lbl-drain-e2-1', x: 1180, y: 154, text: 'ДРЕН Е-2', className: 'utility-label' },
    { id: 'lbl-drain-e2-2', x: 1180, y: 173, text: 'ДРЕНАЖ', className: 'utility-label' },
    { id: 'lbl-steam-k2', x: 1140, y: 232, text: 'ОТПАРНОЙ ПАР К-2', className: 'utility-label', textAnchor: 'middle' },
  ],
};

export const BUILTIN_PRESETS: MnemoschemeConfig[] = [
  DEFAULT_MNEMOSCHEME_PRESET,
];
